### PR TITLE
Spec Typedef

### PR DESCRIPTION
**Pull request by callensm**
Starting point for a type-safe specification based on the current Anchor implementation of IDLs, without the components to be removed as discussed in the conversation (seeds, PDA inference, etc).

Combined with the information gathered in #1 , we can form a base level of how it should be defined given today's most frequent use-cases.

Open for discussion on the field-level type abstractions.

### CODE REVIEW

**Comment by callensm** [comment]
@thlorenz can you add to this what shank appends?

**Comment by thlorenz** [comment]
@callensm aside from the metadata shank adds specific properties to and the fact that instruction accounts are marked as `optional` instead of `isOptional` (to not limit this field to `bool`, but allow supplying an _optional account strategy_ later) shank doesn't change/add anything afaik.

But I'll have a closer look and double check + update/add to what you have.

**Comment by ngundotra** [comment]
We should probably recursively define some of these types.

https://github.com/coral-xyz/anchor/blob/master/ts/packages/anchor/src/idl.ts

Has `IdlField` & `IdlType` recursively defined. I can PR in some changes

**Comment by thlorenz** [comment]
Looking at this closer I realize that the _zod_ syntax is very hard to read esp. since we need it to facilitate discussions.

Given that [ts-to-zod](https://github.com/fabien0102/ts-to-zod) exists I'd recommend writing + discussing the types via TypeScript type Annotations.
We can then include a _build_ script that generates the _zod_ for them (but we'd consider it a built/generated artifact, not something we'd manually edit).

The definitions, esp. for types at this point are still fairly incomplete and I'd fill lots details in, but wanted to check you WRT the above as in that case I'll write them fairly similar to how they already exist in anchor/solita TypeScript code.

**Comment by callensm** [comment]
> Looking at this closer I realize that the _zod_ syntax is very hard to read esp. since we need it to facilitate discussions.
> 
> Given that [ts-to-zod](https://github.com/fabien0102/ts-to-zod) exists I'd recommend writing + discussing the types via TypeScript type Annotations. We can then include a _build_ script that generates the _zod_ for them (but we'd consider it a built/generated artifact, not something we'd manually edit).
> 
> The definitions, esp. for types at this point are still fairly incomplete and I'd fill lots details in, but wanted to check you WRT the above as in that case I'll write them fairly similar to how they already exist in anchor/solita TypeScript code.

I'm total fine with this, as long as `ts-to-zod` is fully featured for generating `zod` schemas.

@ngundotra any thoughts?

**Comment by ngundotra** [comment]
@callensm @thlorenz I'm in favor of writing the Typescript based interface first, then the Zod / validating schema. 

Typescript seems most commonly understood + easiest to read. I am down to support @thlorenz 's approach of creating build scripts from "master" Typescript definitions for our schema.

Quick note on `ts-to-zod`: it's not *fully* featured, so it will require some manual maintenance to export valid zod `IdlSchema`

**Comment by ngundotra** [comment]
@thlorenz do you mind Draft PRing your suggested breakup via the Typescript files -> zod? Doesn't have to be perfect, just something to share what you're thinking.

I think that would be very helpful for us, especially since nothing's been merged in yet

**Comment by thlorenz** [comment]
@ngundotra Sure can do that.
I'll mainly base this on the types you already added from anchor combined with what I have in solita.
Since you mentioned, zod may have problems with recursive defs I may not be able to generate the zod files at this point but I'll give it a try.

@callensm I'm on the same page regarding the benefit of a validator, but in case auto-generation of zod from TypeScript gives us issues I'd like to focus on it later for the following reasons:

- we're early in this and I'd like us to focus on a readable spec that we can iterate on with the least friction so we can iterate fast
- TypeScript types are known to many of us and IDEs support them + they cover the _grammar tree_ requirement since they're part of the TypeScrpt language
- validation is not necessary during the first iteration of this spec, thus we can add that _after_ we got the first version of the spec fleshed out
- packaging a validator into an npm package will be very useful and I expect there to be more utility packages around this, but all this could come later IMO

Main idea being: let's iterate step by step and keep each step as simple and frictionless as possible.

**Comment by ngundotra** [comment]
I'm a fan of breaking up the spec bit by bit via issues, starting with the top-level and working our way down. 

If this looks good to @thlorenz let's merge it in.

Let's discuss IDL top-level changes here: https://github.com/solana-idl-foundation/solana-idl-spec/issues/12

**Comment by thlorenz** [comment]
Yeah, I'm fine with merging this in for now and iterating via followup PRs + discussions.

**Pull request merged**
