### PR TITLE
Add typed zod schemas

### PR DESCRIPTION
**Pull request by ngundotra**
Add Idl types in from anchor-ts package, and add some explicit recursive typing.

### CODE REVIEW

**Comment by ngundotra** [comment]
Going to fix merge conflicts later, just wanted to show what I was thinking

**Comment by callensm** [comment]
want to merge this so the types are in and then work from there with the examples?

**Comment by thlorenz** [comment]
Nice!
@ngundotra could you try to generate the zod parts from the TypeScript types (like I discussed in #2 )?
Then we could include those inside a `zod` subfolder to separate generated files.

I hope this works since I wouldn't want us to have to manually update the spec in two places, but I can ready the TypeScript definitions much easier :)

**Comment by ngundotra** [comment]
@thlorenz! Hey yes. The issue is that the `IdlType` typescript Type itself is recursive, so that has to be manually crafted using `z.lazy(() => z.object({...})`. `ts-to-zod` does not support "complex circular dependencies" so any other typescript Type that references `IdlType` has to be manually crafted as well 😪.


I'm in favor of posting only the Typescript definitions at first + along with validation requirements, and then writing the validation code later.

**Pull request merged**
